# Generated by Django 4.0.4 on 2022-05-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('link_pag', models.CharField(max_length=500)),
                ('link_linkedin', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituto', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=500)),
                ('anoRealizado', models.IntegerField()),
                ('linkGitHub', models.CharField(max_length=500)),
                ('linkYT', models.CharField(max_length=500)),
                ('tecnologia', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='ano_letivo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='ects',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='link_web',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='raking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='semestre',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='topicos_abordados',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_teorica',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docentes_praticas',
            field=models.ManyToManyField(related_name='cadeiras', to='portfolio.professor'),
        ),
    ]
