# Generated by Django 4.0.4 on 2022-05-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_professor_projeto_cadeira_ano_letivo_cadeira_ects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='linkYT',
        ),
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
