# Generated by Django 4.0.4 on 2022-05-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_projeto_linkyt_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituto', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='static/portfolio/images')),
                ('anoRealizado', models.IntegerField()),
                ('participantes', models.CharField(max_length=100)),
                ('linkGitHub', models.CharField(max_length=500)),
                ('tecnologia', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
