# Generated by Django 4.0.4 on 2022-05-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_delete_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tecnologia',
        ),
        migrations.AddField(
            model_name='project',
            name='cadeira',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
