# Generated by Django 4.0.4 on 2022-05-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_tituto_project_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagem',
            field=models.ImageField(upload_to='static/portfolio/imagens'),
        ),
    ]
