# Generated by Django 4.0.4 on 2022-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_project_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descricao', models.TextField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, upload_to='static/portfolio/images')),
                ('autor', models.CharField(max_length=40)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('texto', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
