# Generated by Django 4.0.4 on 2022-05-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('linklusofona', models.CharField(default='1', max_length=1000)),
                ('linklinkedin', models.CharField(default='1', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('apelido', models.CharField(max_length=20)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('acronimo', models.CharField(blank=True, max_length=10)),
                ('ano', models.IntegerField()),
                ('criador', models.CharField(max_length=40)),
                ('logotipo', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(max_length=500)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('sumario', models.TextField(max_length=1000)),
                ('linkGitHub', models.CharField(max_length=1000)),
                ('linkYoutube', models.CharField(max_length=1000)),
                ('linkRelatorio', models.CharField(max_length=1000)),
                ('ano', models.IntegerField()),
                ('autor', models.CharField(max_length=70)),
                ('orientador', models.CharField(max_length=70)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='cadeira',
            new_name='chair',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='link_web',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='descricao',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadeira',
            name='link_cadeira',
            field=models.CharField(default='1', max_length=1000),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='portfolio.project'),
        ),
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='1', max_length=70)),
                ('descricao', models.CharField(default='1', max_length=100)),
                ('cadeira', models.CharField(default='1', max_length=40)),
                ('projetos', models.ManyToManyField(blank=True, to='portfolio.project')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='linguagens',
            field=models.ManyToManyField(blank=True, to='portfolio.tecnologia'),
        ),
    ]
