# Generated by Django 4.0.4 on 2022-05-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_person_pontuacaoquizz_tecnologia_tfc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='imagem',
            field=models.ImageField(default='1', upload_to='static/portfolio/imagens'),
        ),
        migrations.AlterField(
            model_name='education',
            name='logotipo',
            field=models.ImageField(upload_to='static/portfolio/imagens'),
        ),
    ]
