# Generated by Django 4.0.4 on 2022-05-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_education_imagem_alter_education_logotipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lingua',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/portfolio/imagens'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='static/portfolio/imagens'),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='logotipo',
            field=models.ImageField(upload_to='static/portfolio/imagens'),
        ),
    ]
