# Generated by Django 4.0.4 on 2022-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_lingua_alter_new_imagem_alter_noticia_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
