# Generated by Django 4.0.4 on 2022-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_education_imagem_alter_education_logotipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfc',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='orientador',
        ),
        migrations.AddField(
            model_name='tfc',
            name='orientador',
            field=models.ManyToManyField(to='portfolio.person'),
        ),
    ]
