# Generated by Django 4.0.4 on 2022-06-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_tfc_imagem_remove_tfc_orientador_tfc_orientador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfc',
            old_name='imagem',
            new_name='imagem2',
        ),
    ]
